name: Git Leaks
on:
  push:
jobs:
  gitleaks:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Run Gitleaks
          run: |
            gitleaks detect --redact -v --exit-code=2 --report-format=sarif --report-path=results.sarif --log-level=debug --log-opts=-1000
  